[package]
name = "theorem_proving_in_lean"
version = "0.1"
lean_version = "leanprover-community/lean:3.18.4"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "1930601cb39d7e3e1895f32c8f1915e35d7036be"}
