name: mdbook deploy to github pages

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download mdbook for Lean
      shell: bash
      run: |
        curl -O --location https://github.com/leanprover/mdBook/releases/download/v0.4.6/mdbook-linux.tar.gz
        tar xvf mdbook-linux.tar.gz
        ./mdbook-linux/mdbook --help
        ldd ./mdbook-linux/mdbook
    - name: Run mdbook build
      shell: bash
      run: |
        ./mdbook-linux/mdbook build
        rm -rf ./out/.git
        rm -rf ./out/.github
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: out
    - name: Deploy to Netlify hosting
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: out
        production-branch: master
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: |
          ${{ github.event_name == 'pull_request' && format('pr#{0}: {1}', github.event.number, github.event.pull_request.title) || format('ref/{0}: {1}', github.ref_name, steps.deploy-info.outputs.message) }}
        alias: ${{ steps.deploy-info.outputs.alias }}
        enable-commit-comment: false
        enable-pull-request-comment: false
        github-deployment-environment: "lean-lang.org/theorem_proving_in_lean4"
        fails-without-credentials: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: "51300c89-2f6c-4bba-a575-8cf12e434502"
